#!/usr/bin/python3

import time
import signal

from multiprocessing.pool import ThreadPool
pool = ThreadPool(processes=1)

import sys
sys.path.append('/home/pi/python')
from Engine import *

r = Engine()

from math import *
r.conf_set('send_status_interval', 100)
r.setpos(0,0)
r.speed(80)

#  r.tol = 20
r.tol = 0
#  for i in range(1,5):
	#  print( ((i+1)*100, sin(2*pi * i/10 * 1.0) * 200.0) )
	
#  pool.apply_async( lambda: (time.sleep(3.0), r.t(255)) )
d=710
r.forward(-d)
for i in range(7):
	r.forward(15)
	r.forward(-15)
	#  r.turn(3)
	#  r.turn(-3)
#  time.sleep(1)
r.t(255)
time.sleep(3)
r.t(0)
r.forward(d)

#  while True:
	#  r.move(200,300,200)
	#  r.move(0,0,300)
	#  r.move(400,0,300)
