config_bytes = [
	'distance_regulator',
	'rotation_regulator',
	'enable_stuck',
	'stuck',
	'debug',
	'status_change_report',
	'keep_count',
	'tmr',
	'motor_connected',

]
config_ints = [
	'stuck_distance_jump',
	'stuck_rotation_jump',
	'stuck_distance_max_fail_count',
	'stuck_rotation_max_fail_count',
	'motor_speed_limit',
	'motor_rate_of_change',
	'send_status_interval',
	'motor_const_roc',

]
config_floats = [
	'wheel_distance',
	'wheel_r1',
	'wheel_r2',
	'pid_d_p',
	'pid_d_d',
	'pid_r_p',
	'pid_r_d',
	'vmax',
	'omega',
	'accel',
	'alpha',
	'slowdown',
	'slowdown_angle',
	'angle_speedup',
]
commands = {
	'set_config': 'c',
	'get_config': 'C',
	'move_to': 'N',
	'send_status_and_position': 'P',
	'unstuck': 'U',
	'motor': 'm',
	'send_position': 'p',
	'set_speed': 'V',
	'set_rotation_speed': 'r',
	'move_forward': 'r',
	'relative_rotate': 'T',
	'absolute_rotate': 'A',
	'turn_and_go': 'G',
	'curve': 'Q',
	'hard_stop': 'S',
	'soft_stop': 's',
	'smooth_stop': 't',
	'reset_driver': 'R',
	'kill_regulator': 'H',
	'forward': 'D',
	'set_position_and_orientation': 'I',
	'break': 'i',
}

